site_name: CelesteG1's Docs-as-Code Portfolio 
site_url: https://celesteg1.github.io/mkdocs/
theme:
  name: material
  logo: assets/images/minimal-icon.png
  palette:
    - scheme: default
      primary: teal
      accent: '#00C2CB'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: '#00C2CB'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - toc.integrate

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.mark
  - pymdownx.inlinehilite
  - codehilite
  - pymdownx.highlight

plugins:
  - search
  - markdown-exec
  - macros:
      include_dir: docs
      include_yaml: []
      module_name: main

extra:
  favicon: assets/images/favicon.png
extra_css:
  - css/extra.css
docs_dir: docs
nav:
  - Home: index.md
  - Fictional Examples:
    - Overview: examples/overview.md
    - Post-Trade Automation with Tokenisation and Blockchain:
      - Post-Trade Automation:
        - Introduction: examples/post-trade-automation/pt-auto/introduction.md
        - Why Traditional Post-Trade Processes Are a Bottleneck: examples/post-trade-automation/pt-auto/why-traditional-post-trade-processes-are-a-bottleneck.md
        - What is Post-Trade Automation?: examples/post-trade-automation/pt-auto/what-is-post-trade-automation.md
        - What is Tokenisation?: examples/post-trade-automation/pt-auto/what-is-tokenisation.md
        - Why Tokenise Financial Assets?: examples/post-trade-automation/pt-auto/why-tokenise-financial-assets.md
        - How ABC-Labs Enable Post-Trade Automation: examples/post-trade-automation/pt-auto/how-abc-labs-enable-post-trade-automation.md
        - Why it Matters: examples/post-trade-automation/pt-auto/conclusion.md
      - Token Lifecycle:
        - Introduction: examples/post-trade-automation/token-lifecycle/introduction.md
        - What is a Token Lifecycle?: examples/post-trade-automation/token-lifecycle/what-is-a-token-lifecycle.md
        - Why Tokenisation Matters: examples/post-trade-automation/token-lifecycle/why-tokenisation-matters.md
        - Token Lifecycle Stages & API Mapping: examples/post-trade-automation/token-lifecycle/token-lifecycle-stages-and-api-mapping.md
        - Token Lifecycle in Practice:
          - 1. Minting: examples/post-trade-automation/token-lifecycle/lifecycle-in-practice/lip-minting.md
          - 2. Transfer: examples/post-trade-automation/token-lifecycle/lifecycle-in-practice/lip-transfer.md
          - 3. Burning: examples/post-trade-automation/token-lifecycle/lifecycle-in-practice/lip-burning.md
          - 4. Balance Check: examples/post-trade-automation/token-lifecycle/lifecycle-in-practice/lip-balance-check.md
      - How-To's: 
        - How-To Mint (Create) a Token: examples/post-trade-automation/how-tos/how-to-mint-a-token.md
        - How-To Transfer Tokens: examples/post-trade-automation/how-tos/how-to-transfer-tokens.md
        - How-To Burn (Destroy) Tokens: examples/post-trade-automation/how-tos/how-to-burn-tokens.md
        - How-To Check a Token Balance: examples/post-trade-automation/how-tos/how-to-check-a-token-balance.md
      - Reference Guides:
        - API Reference:
          - API Overview: examples/post-trade-automation/references/api/api-overview.md
          - Burn Token: examples/post-trade-automation/references/api/api-burn-token.md
          - Check Token Balance: examples/post-trade-automation/references/api/api-check-token-balance.md
          - Mint Token: examples/post-trade-automation/references/api/api-mint-token.md
          - Transfer Token: examples/post-trade-automation/references/api/api-transfer-token.md
        - Glossary of Key Concepts: examples/post-trade-automation/references/glossary-of-terms/glossary-of-terms.md
  - Official Docs:
    - Overview: official-docs/overview.md
  - Research & Development (R&D):
    - Overview: research/overview.md
          